const flock=[['base','Cock Nemesis'],['hulk','Hulk Nemesis'],['venom','Venom Nemesis'],['boss','King Nemesis']];
const previews=[];
function save(canvas,name){canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}
Promise.all(['walk','mutant','crystal'].flatMap(prefix=>(prefix==='crystal'?[...flock,['runner','Crystal Speedpeck'],['hexqueen','Crystal Hex Queen']]:flock).map(async([key,name])=>{
 const label=(prefix==='mutant'?'Mutated ':prefix==='crystal'?'Crystal ':'')+name.replace(/^Crystal /,''),src=`assets/${prefix}-${key}.webp`;
 const card=document.createElement('article'),title=document.createElement('h2');title.textContent=label;card.append(title);document.querySelector('#gallery').append(card);
 const frames=await (prefix==='crystal'?loadActionSheet:loadWalkSheet)(src),canvas=document.createElement('canvas');canvas.width=frames[0].width;canvas.height=frames[0].height;canvas.setAttribute('aria-label',label+' walking preview');card.prepend(canvas);
 const preview={canvas,frames,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,frame:0};previews.push(preview);
 for(const [text,action] of [['Play / pause walk',()=>preview.playing=!preview.playing],['Save current frame',()=>save(frames[preview.frame],label+'-frame-'+(preview.frame+1))],['Save four-frame sheet',async()=>{const sheet=prefix==='crystal'?await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);resolve(c);};im.onerror=reject;im.src=src;}):await loadCharacter(src);save(sheet,label+'-sheet');}]]){const button=document.createElement('button');button.textContent=text;button.onclick=action;card.append(button);}
}))).then(()=>document.querySelector('#status').textContent='Fourteen characters ready. Frame order: top-left, top-right, bottom-left, bottom-right.').catch(()=>document.querySelector('#status').textContent='A character could not load. Refresh to retry.');
function animate(time){for(const p of previews){if(p.playing)p.frame=Math.floor(time/170)%4;const c=p.canvas.getContext('2d');c.clearRect(0,0,p.canvas.width,p.canvas.height);c.drawImage(p.frames[p.frame],0,0);}requestAnimationFrame(animate);}requestAnimationFrame(animate);
