/* Local sprite choreography; no flashing full-screen white frames or new songs. */
window.drawKnollCampaign=function(c,g,art,vfx,time){
 const K=KnollDefense,draw=(im,x,y,size,alpha=1)=>{if(!im)return;c.save();c.globalAlpha*=alpha;c.drawImage(im,x-size/2,y-size,size,size);c.restore();};
 for(const a of g.allies){draw(art.demon[a.inCombat?(a.cooldown>.4?2:3):Math.floor(a.progress/8)%2],a.x,a.y,120);c.fillStyle='#111d18';c.fillRect(a.x-25,a.y+5,50,5);c.fillStyle='#97ffb2';c.fillRect(a.x-25,a.y+5,50*Math.max(0,a.hp/a.maxHp),5);c.fillStyle='#c5ffbf';c.font='bold 10px Segoe UI';c.textAlign='center';c.fillText('ALLY',a.x,a.y+21);}
 c.textAlign='left';
 for(const e of g.effects){if(e.kind==='heal'){const q=1-e.age/e.life;c.save();c.globalAlpha=q*.7;c.strokeStyle='#a9ffd8';c.lineWidth=2;c.beginPath();c.moveTo(e.x,e.y);c.quadraticCurveTo((e.x+e.tx)/2,Math.min(e.y,e.ty)-40,e.tx,e.ty);c.stroke();for(let i=0;i<5;i++){const f=(e.age+i*.2)%1;vfx.glow(e.x+(e.tx-e.x)*f,e.y+(e.ty-e.y)*f-Math.sin(f*Math.PI)*30,5,'#b3ffdf',.7);}c.restore();}
  if(e.kind==='uppercut'){if(!art.neon){art.neon=art.phil.map(im=>{const b=document.createElement('canvas');b.width=im.width;b.height=im.height;const x=b.getContext('2d');x.drawImage(im,0,0);x.globalCompositeOperation='source-in';x.fillStyle='#5ceaff';x.fillRect(0,0,b.width,b.height);return b;});}const f=e.age/e.life,frame=f<.65?2:3;c.save();c.globalCompositeOperation='lighter';for(let j=3;j>=0;j--)draw(art.neon[frame],e.x-20-j*10,e.y-Math.sin(f*Math.PI)*48+j*12,128,(1-f)*(j===0?.75:.12));vfx.glow(e.x,e.y-105-Math.sin(f*Math.PI)*50,28,'#61eaff',1-f);c.restore();}
 }
 for(const a of g.conversions){const t=a.target,o=a.owner,q=1-a.left/2;c.save();c.strokeStyle='#b4ffdf';c.lineWidth=2;c.setLineDash([8,7]);c.lineDashOffset=-time*30;c.beginPath();c.moveTo(o.x,o.y-90);c.quadraticCurveTo((o.x+t.x)/2,t.y-160,t.x,t.y-45);c.stroke();c.setLineDash([]);c.strokeStyle='#bb8dff';c.beginPath();c.ellipse(t.x,t.y,30,12,0,-Math.PI/2,-Math.PI/2+q*Math.PI*2);c.stroke();vfx.glow(t.x,t.y-40,50,'#b69aff',q*.5);c.restore();}
 if(g.ultimate){const u=g.ultimate,t=u.age;c.save();c.fillStyle='#03180ee0';c.fillRect(0,0,1200,70);c.fillRect(0,720,1200,80);
  if(t<2.1){c.fillStyle='#06130b99';c.fillRect(0,70,1200,650);const frame=t<.4?0:t<1.45?1:2;vfx.glow(600,420,240,'#a2dc68',.65);draw(art.reno[frame],600,680,530);c.fillStyle='#f3eccb';c.font='bold 34px Georgia';c.textAlign='center';c.fillText('RENO MO',600,55);c.font='18px Georgia';c.fillText(t<1.45?'The roots remember.':'THORN RECKONING',600,762);}
  else{const end=Math.min(1,(t-2)/2)*K.pathLength;c.lineCap='round';for(const [width,color] of [[24,'#172b0a'],[16,'#527b32'],[5,'#c5df83']]){c.strokeStyle=color;c.lineWidth=width;c.beginPath();for(let p=0;p<=end;p+=7){const at=K.position(p);if(p===0)c.moveTo(at.x,at.y);else c.lineTo(at.x,at.y);}c.stroke();}for(let p=15;p<end;p+=30){const at=K.position(p),next=K.position(Math.min(K.pathLength,p+3)),a=Math.atan2(next.y-at.y,next.x-at.x);c.save();c.translate(at.x,at.y);c.rotate(a);c.fillStyle='#abca6b';c.beginPath();c.moveTo(-6,0);c.lineTo(7,-25*(p%60<30?1:-1));c.lineTo(5,0);c.fill();c.restore();}const head=K.position(end);vfx.glow(head.x,head.y,60,'#a4e960');draw(art.reno[3],1080,735,170);c.fillStyle='#eef7c5';c.font='bold 24px Georgia';c.textAlign='center';c.fillText('THORN RECKONING',600,46);c.font='16px Segoe UI';c.fillText(u.hit.size+' / '+u.targets.length+' enemies hit · 50% health removed',600,765);}
  c.restore();
 }
};
