(function(){
  'use strict';
  const K=window.KnollDefense, game=new K.Game(), canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
  const $=s=>document.querySelector(s), imgs={};
  const art={shrine:'assets/pear-shrine.webp',knowme:'assets/knowme.webp',host:'assets/host.webp',sailor:'assets/sailor.webp',maahaa:'assets/maahaa.webp',fordenad:'assets/fordenad.webp',lady:'assets/lady.webp',phil:'assets/phil.webp',reno:'assets/reno.webp',board:'assets/forest-expanded.webp',burnt:'assets/forest-burnt.webp',citadel:'assets/eclipse-citadel.webp'};
  const cards=[['knowme','1'],['host','2'],['sailor','3'],['maahaa','4'],['fordenad','5'],['lady','6'],['phil','7']]; let selected='knowme', selectedTower=null, placing=false, paused=false, speed=1, last=0, raf=0, toastTimer=0, sound=false;
  const sfx=new KnollAudio(),vfx=new KnollVFX(ctx),walks={},actions={};let visualTime=0;
  let ready=false;
  function saveCheckpoint(){if(!ready)return;try{if(game.status==='lost'||game.status==='won')localStorage.removeItem(KnollCheckpoint.key);else{const data=KnollCheckpoint.capture(game);if(data)localStorage.setItem(KnollCheckpoint.key,data);}}catch{}}
  setInterval(saveCheckpoint,1000);window.addEventListener('pagehide',saveCheckpoint);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveCheckpoint();});
  const quick=document.createElement('div');quick.id='towerQuick';quick.hidden=true;quick.setAttribute('role','group');quick.setAttribute('aria-label','Selected tower actions');quick.innerHTML='<strong id="quickName"></strong><button id="quickUpgrade"></button><button id="quickDelete"></button><button id="quickClose" aria-label="Close tower actions">×</button>';$('#arena').after(quick);
  function updateQuick(){const t=selectedTower;quick.hidden=!t||!game.towers.includes(t);if(quick.hidden)return;$('#quickName').textContent=K.TYPES[t.type].name+' · '+roman[t.level];$('#quickUpgrade').textContent=t.level>=3?'Fully upgraded':'Upgrade · ✧ '+K.upgradeCost(t);$('#quickUpgrade').disabled=t.level>=3||game.gold<K.upgradeCost(t)||['lost','won'].includes(game.status);$('#quickDelete').textContent='Delete · refund ✧ '+Math.floor(t.spent*.5)+' (50%)';}
  $('#quickUpgrade').onclick=()=>{if(selectedTower&&game.upgrade(selectedTower.id)){updateInspector();updateQuick();saveCheckpoint();toast('Guardian upgraded!');}};
  $('#quickDelete').onclick=()=>{const t=selectedTower;if(t&&game.sell(t.id)){selectedTower=null;updateInspector();updateQuick();refreshPads();saveCheckpoint();toast('Tower deleted · 50% refunded.');}};
  $('#quickClose').onclick=()=>{selectedTower=null;quick.hidden=true;};
  canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*1200/r.width,y=(e.clientY-r.top)*800/r.height;const t=[...game.towers].sort((a,b)=>b.y-a.y).find(t=>Math.abs(x-t.x)<55&&y>=t.y-150&&y<=t.y+25);if(t)setTower(t);else{selectedTower=null;quick.hidden=true;}});
  let touchStart=0;document.addEventListener('touchstart',e=>{touchStart=e.touches[0]?.clientY||0;},{passive:true});document.addEventListener('touchmove',e=>{if(e.touches.length===1&&window.scrollY<=0&&e.touches[0].clientY>touchStart&&!e.target.closest('dialog,.roster'))e.preventDefault();},{passive:false});
  const roman=['','I','II','III'];
  // A viewport-filling play mode also works on phones without Fullscreen API support.
  const playBar=document.createElement('div');playBar.className='play-bar';playBar.innerHTML='<button id="playViewBtn" aria-pressed="false">⛶ Play view</button><button id="gnomeDrawerBtn" aria-expanded="false" aria-controls="roster">Gnomes ▾</button><span id="playResources" role="status"></span><button id="playWaveBtn">Send wave</button>';
  $('.battle-column').prepend(playBar);
  let playView=false,drawerOpen=false;
  function setDrawer(open){drawerOpen=open;document.body.classList.toggle('gnome-drawer-open',open);$('#gnomeDrawerBtn').setAttribute('aria-expanded',String(open));}
  function setPlayView(on){playView=on;document.body.classList.toggle('play-view',on);$('#playViewBtn').textContent=on?'✕ Exit play view':'⛶ Play view';$('#playViewBtn').setAttribute('aria-pressed',String(on));setDrawer(false);if(!on)$('#playViewBtn').focus();}
  $('#playViewBtn').onclick=()=>setPlayView(!playView);
  $('#gnomeDrawerBtn').onclick=()=>setDrawer(!drawerOpen);
  $('#playWaveBtn').onclick=()=>$('#waveBtn').click();
  $('#roster').addEventListener('click',e=>{const card=e.target.closest('[data-type]');if(card&&(K.TYPES[card.dataset.type].unlock||1)<=game.stage)setDrawer(false);});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(drawerOpen)setDrawer(false);else if(playView)setPlayView(false);}});
  $('#speedBtn').setAttribute('aria-label','Game speed: 1 times. Click to change');
  $('#speedBtn').addEventListener('click',e=>{e.stopImmediatePropagation();speed=[1,1.5,2][([1,1.5,2].indexOf(speed)+1)%3];$('#speedBtn').textContent=speed+'×';$('#speedBtn').setAttribute('aria-label','Game speed: '+speed+' times. Click to change');toast(speed+'× defense speed');},true);
  function loadAssets(){return Promise.all([loadWalks(),...['base','runner','hulk','venom','boss','hexqueen'].map(async k=>walks['crystal-'+k]=await loadActionSheet('assets/crystal-'+k+'.webp')),...['lady','phil','reno','demon'].map(async k=>actions[k]=await loadActionSheet('assets/'+k+'-actions.webp')),...Object.entries(art).map(async([k,src])=>{if(['nibble','brute','boss','venom'].includes(k)){imgs[k]=await loadCharacter(src);return;}imgs[k]=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(src));im.src=src;});})]);}
  async function loadWalks(){await Promise.all(['base','hulk','venom','boss'].flatMap(kind=>['walk','mutant'].map(async prefix=>{walks[prefix+'-'+kind]=await loadWalkSheet('assets/'+prefix+'-'+kind+'.webp');})));}
  function makeRoster(){
    $('#roster').innerHTML=cards.map(([type,key])=>{const t=K.TYPES[type];return `<button class="tower-card" data-type="${type}"><div class="card-art"><img src="${art[type]}" alt="${t.name} gnome"><span class="card-key">${key}</span></div><div class="card-copy"><strong>${t.name}</strong><small>${t.power}</small><span class="card-cost">✧ ${t.cost}<em>+</em></span></div></button>`}).join('');
    document.querySelectorAll('.tower-card').forEach(b=>b.onclick=()=>selectType(b.dataset.type));
  }
  function selectType(type){if((K.TYPES[type].unlock||1)>game.stage){toast('Unlocks in Level '+K.TYPES[type].unlock);return;}selected=type;selectedTower=null;placing=true;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));updateInspector();paint();}
  function setTower(t){selectedTower=t;placing=false;selected=t.type;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===selected));updateInspector();paint();}
  function updateInspector(){const t=selectedTower, type=t?t.type:selected, d=K.TYPES[type], s=t?K.stats(t):{damage:d.damage,range:d.range,interval:d.interval};$('#inspectorEyebrow').textContent=t?'PLACED GUARDIAN':'MEET YOUR GUARDIAN';$('#levelLabel').textContent=t?roman[t.level]:'I';$('#towerName').textContent=d.name;$('#towerTitle').textContent=d.title.toUpperCase();$('#towerDescription').textContent=d.description;$('#powerBadge').textContent=d.power.toUpperCase();$('#portraitImage').src=art[type];$('#portraitImage').alt=d.name+' guardian';document.querySelector('.tower-stats span').textContent=type==='lady'?'HEAL / SEC':'DAMAGE';$('#damageStat').textContent=type==='lady'?4*(t?t.level:1):Math.round(s.damage);$('#targetBtn').hidden=type==='lady';$('#rangeStat').textContent=Math.round(s.range);$('#rateStat').textContent=(1/s.interval).toFixed(1)+'/s';$('#towerExtra').hidden=!t;$('#killStat').textContent=t?`${t.kills} takedowns · HP ${Math.ceil(t.hp)}/${t.maxHp}`:'';$('#targetBtn').textContent=t?`Target: ${t.targetMode} ↔`:'';$('#actionBtn').hidden=!!t;$('#sellBtn').hidden=!t;$('#sellBtn').textContent=t?`Delete tower · 50% refund ✧ ${Math.floor(t.spent*.5)}`:'';$('#placementNote').textContent=t?'Select a placed guardian to inspect or upgrade.':`Then choose an empty stone clearing · ✧ ${d.cost}`;if(t){const up=K.upgradeCost(t);$('#actionBtn').hidden=false;$('#actionBtn').innerHTML=t.level<3?`Upgrade to ${roman[t.level+1]} <span>✧ ${up}</span>`:'Fully upgraded';$('#actionBtn').disabled=t.level>=3||game.gold<up;$('#actionBtn').dataset.action='upgrade';}else{$('#actionBtn').hidden=false;$('#actionBtn').disabled=game.gold<d.cost;$('#actionBtn').innerHTML=`Recruit guardian <span>✧ ${d.cost}</span>`;$('#actionBtn').dataset.action='recruit';}}
  function makePads(){const wrap=$('#pads');wrap.innerHTML=K.PADS.map((p,i)=>`<button class="pad" data-pad="${i}" aria-label="Stone clearing ${i+1}"></button>`).join('');wrap.querySelectorAll('.pad').forEach((b,i)=>b.onclick=()=>{const t=game.towers.find(x=>x.pad===i);if(t){setTower(t);return}if(!placing){toast('Choose a guardian first.');return}const placed=game.place(selected,i);if(!placed)toast(game.gold<K.TYPES[selected].cost?'Not enough gold yet.':'That clearing is unavailable.');else{toast(`${K.TYPES[selected].name} took the clearing.`);selectedTower=placed;placing=false;updateInspector();}refreshPads();paint();});refreshPads();}
  function refreshPads(){document.querySelectorAll('.pad').forEach((b,i)=>{const t=game.towers.find(x=>x.pad===i),p=K.PADS[i];b.style.left=(p.x/12)+'%';b.style.top=(p.y/8)+'%';b.classList.toggle('occupied',!!t);b.title=t?`${K.TYPES[t.type].name} · level ${t.level}`:`Build on clearing ${i+1}`});}
  function drawMap(){const map=game.stage===3?imgs.citadel:game.stage===2?imgs.burnt:imgs.board;ctx.drawImage(map,0,0,map.width,map.height*.2,0,0,1200,224);ctx.drawImage(map,0,map.height*.2,map.width,map.height*.8,0,224,1200,640);if(game.stage===2)drawFlames();sprite(imgs.shrine,1110,338,176,176);}
  function drawFlames(){ctx.save();ctx.globalCompositeOperation='screen';for(let i=1;i<K.PATH.length-1;i+=2){const p=K.PATH[i],n=K.PATH[i+1],len=Math.hypot(n[0]-p[0],n[1]-p[1]);for(const side of [-1,1]){const x=p[0]-(n[1]-p[1])/len*48*side,y=p[1]+(n[0]-p[0])/len*48*side;for(let j=0;j<3;j++){const phase=visualTime*5+i+j*2,height=20+12*Math.sin(phase);ctx.fillStyle=j===2?'#ffe9a9bb':j===1?'#ffad3199':'#fa431766';ctx.beginPath();ctx.moveTo(x-9+j*2,y);ctx.quadraticCurveTo(x-16+Math.sin(phase)*7,y-height*.6,x+Math.sin(phase)*9,y-height-12);ctx.quadraticCurveTo(x+16,y-height*.4,x+9-j*2,y);ctx.fill();}}}ctx.restore();}
  function pathStroke(){ctx.beginPath();ctx.moveTo(...K.PATH[0]);for(const p of K.PATH.slice(1))ctx.lineTo(...p);}
  function drawPads(){for(let i=0;i<K.PADS.length;i++){const p=K.PADS[i],t=game.towers.find(x=>x.pad===i);if(t)continue;ctx.fillStyle='rgba(210,225,168,.35)';ctx.beginPath();ctx.ellipse(p.x,p.y,31,19,0,0,7);ctx.fill();ctx.strokeStyle='rgba(56,82,50,.65)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#d8ddbd';ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.fillText(String(i+1),p.x,p.y+4);ctx.textAlign='left';}}
  function sprite(im,x,y,w,h,alpha=1){if(!im)return;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x-w/2,y-h,w,h);ctx.restore()}
  function drawTowers(towers=game.towers){for(const t of towers){
    ctx.fillStyle='#182820';ctx.fillRect(t.x-25,t.y+23,50,5);ctx.fillStyle=t.hp<t.maxHp*.4?'#ff795e':'#91d99d';ctx.fillRect(t.x-25,t.y+23,50*t.hp/t.maxHp,5);
    const d=K.TYPES[t.type],scale=1+(t.level-1)*.06,clock=game.time+t.id,bob=t.type==='host'?Math.sin(clock*3)*4:Math.sin(clock*2)*1.5;
    ctx.fillStyle='#162f1e55';ctx.beginPath();ctx.ellipse(t.x,t.y+2,33,11,0,0,7);ctx.fill();
    const nearest=game.enemies.filter(e=>e.hp>0).reduce((best,e)=>!best||Math.hypot(e.x-t.x,e.y-t.y)<Math.hypot(best.x-t.x,best.y-t.y)?e:best,null);
    if(nearest&&Math.abs(nearest.x-t.x)>12&&!(t.frozenUntil>game.time))t.facing=nearest.x<t.x?-1:1;
    ctx.save();if(t.facing===-1){ctx.translate(t.x*2,0);ctx.scale(-1,1);}
    sprite(actions[t.type]?actions[t.type][t.castUntil>game.time?Math.min(3,1+Math.floor((game.time-t.castStart)/.65)):0]:imgs[t.type],t.x-(t.type==='sailor'?t.recoil*7:0),t.y-bob,(actions[t.type]?150:105)*scale,145*scale);
    ctx.restore();
    ctx.save();ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.shadowColor=d.color;ctx.shadowBlur=12;ctx.globalAlpha=.55;
    if(t.type==='knowme'){for(let i=0;i<6;i++){const a=clock+i*1.05;ctx.beginPath();ctx.arc(t.x+Math.cos(a)*32,t.y-55+Math.sin(a)*18,2+i%2,0,7);ctx.fill();}}
    if(t.type==='host'){ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t.x,t.y-65,42,13,Math.sin(clock)*.4,0,Math.PI*2);ctx.stroke();}
    if(t.type==='maahaa'){ctx.translate(t.x+17,t.y-120*scale);ctx.rotate(clock*.5);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(18+t.recoil*12,0);ctx.stroke();}}
    if(t.type==='fordenad'){for(let i=0;i<4;i++){const a=clock*.7+i*Math.PI/2;ctx.save();ctx.translate(t.x+Math.cos(a)*27,t.y-20+Math.sin(a)*9);ctx.rotate(a);ctx.beginPath();ctx.ellipse(0,0,6,2,0,0,7);ctx.fill();ctx.restore();}}
    if(t.type==='sailor'&&t.recoil>0){ctx.globalAlpha=t.recoil*.5;ctx.fillStyle='#e5dab8';ctx.beginPath();ctx.arc(t.x+32,t.y-73-(1-t.recoil)*20,4+(1-t.recoil)*12,0,7);ctx.fill();}
    ctx.restore();
    if(t.frozenUntil>game.time||t.hexUntil>game.time||t.poisonWardUntil>game.time){
      const frozen=t.frozenUntil>game.time,hex=t.hexUntil>game.time,color=frozen?'#98eeff':hex?'#f591ff':'#ffe5a1';
      ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=9;
      if(frozen){for(let j=-1;j<=1;j++){ctx.beginPath();ctx.moveTo(t.x+j*28-10,t.y);ctx.lineTo(t.x+j*28-6,t.y-85);ctx.lineTo(t.x+j*28+4,t.y-115);ctx.lineTo(t.x+j*28+11,t.y);ctx.closePath();ctx.globalAlpha=.2;ctx.fill();ctx.globalAlpha=.8;ctx.stroke();}}
      else{ctx.beginPath();ctx.ellipse(t.x,t.y-30,39,15,0,0,Math.PI*2);ctx.stroke();}
      ctx.globalAlpha=1;ctx.font='bold 11px Segoe UI';ctx.textAlign='center';
      const remaining=(frozen?t.frozenUntil:hex?t.hexUntil:t.poisonWardUntil)-game.time;
      ctx.fillText((frozen?'FROZEN ':hex?'HEXED ':'WARD ')+Math.ceil(remaining)+'s',t.x,t.y+43);ctx.restore();
    }
    ctx.fillStyle=d.color;ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(roman[t.level],t.x,t.y+18);ctx.textAlign='left';
  }}

  function drawEnemies(enemies=game.enemies){for(const e of enemies){if(e.hp<=0)continue;const kind=e.kind==='brute'?'hulk':['boss','venom','hexqueen'].includes(e.kind)?e.kind:e.kind==='runner'&&e.crystal?'runner':'base',frames=walks[(e.crystal?'crystal':e.mutated?'mutant':'walk')+'-'+kind],im=frames[Math.floor(e.progress/10+e.id)%4],h=105*e.size,w=h*im.width/im.height,bob=0;ctx.fillStyle='#10221966';ctx.beginPath();ctx.ellipse(e.x,e.y+2,w*.35,8,0,0,7);ctx.fill();ctx.save();ctx.translate(e.x,e.y);if(e.direction<0)ctx.scale(-1,1);sprite(im,0,bob,w,h);if(e.crystal&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&Math.sin(visualTime*2+e.id*4)>.985){ctx.save();ctx.globalAlpha=.35;const sy=Math.floor(im.height*.42);ctx.drawImage(im,0,sy,im.width,im.height*.07,-w/2+4,-h*.58,w,h*.07);ctx.restore();}ctx.restore();vfx.frozen(e.frozenUntil>game.time?{...e,slowUntil:e.frozenUntil}:e,game.time,h,w);if(e.volleyLeft>0){vfx.glow(e.x,e.y-30,40,'#89f04f',.3);ctx.save();ctx.strokeStyle='#baff70';ctx.beginPath();ctx.ellipse(e.x,e.y,27,9,0,0,7);ctx.stroke();ctx.restore();}if(e.reverseUntil>game.time){vfx.glow(e.x,e.y,28,'#be88ff',.4);ctx.save();ctx.fillStyle='#e2c8ff';ctx.font='bold 19px Segoe UI';ctx.textAlign='center';ctx.fillText('↶',e.x,e.y-h-13);ctx.restore();}ctx.fillStyle='#182820';ctx.fillRect(e.x-22,e.y-h-5,44,4);ctx.fillStyle=e.enraged?'#ff834d':e.kind==='venom'?'#8dff91':e.kind==='boss'?'#ffd569':'#c5e98f';ctx.fillRect(e.x-22,e.y-h-5,44*Math.max(0,e.hp/e.maxHp),4);if(e.slowUntil>game.time||e.poisonUntil>game.time){ctx.strokeStyle=e.poisonUntil>game.time?'#9ff46c':'#8ffff2';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y,24,8,0,0,7);ctx.stroke();}}}
  const freezeBtn=document.createElement('button');freezeBtn.id='freezeBtn';freezeBtn.className='primary';$('#arena').append(freezeBtn);freezeBtn.onclick=()=>{if(!paused&&game.freezeKnowME())toast('KnowME — FIVE-SECOND DEEP FREEZE');};
  const hellfireBtn=document.createElement('button');hellfireBtn.id='hellfireBtn';hellfireBtn.className='primary';$('#arena').append(hellfireBtn);hellfireBtn.onclick=()=>{if(!paused&&game.summonHellfire())toast('Old Sailor — HELLFIRE BARRAGE');};
  const reverseBtn=document.createElement('button');reverseBtn.id='reverseBtn';reverseBtn.className='primary';$('#arena').append(reverseBtn);reverseBtn.onclick=()=>{if(!paused&&game.reverseHost())toast('Host — REVERSE THE FLOCK');};
  const volleyBtn=document.createElement('button');volleyBtn.id='volleyBtn';volleyBtn.className='primary';$('#arena').append(volleyBtn);volleyBtn.onclick=()=>{if(!paused&&game.poisonVolley())toast('Fordenad — POISON VOLLEY');};
  const cleanseBtn=document.createElement('button');cleanseBtn.id='cleanseBtn';cleanseBtn.className='primary';cleanseBtn.hidden=true;cleanseBtn.title='Level 3 · Once per level: cleanse all towers, ward poison for 5 seconds, heal the five most injured by 30% max HP.';cleanseBtn.onclick=()=>{if(!paused&&game.cleanseMaahaa())toast('Maahaa — CLEANSE · poison ward + 30% healing');};
  const powerGrid=document.createElement('div');powerGrid.id='powerGrid';powerGrid.setAttribute('role','group');powerGrid.setAttribute('aria-label','Gnome special powers');powerGrid.append(freezeBtn,hellfireBtn,reverseBtn,volleyBtn,cleanseBtn);$('#arena').append(powerGrid);
  $('#renoBtn').onclick=()=>{if(!paused&&game.summonReno()){$('#arena').scrollIntoView({behavior:'instant',block:'center'});toast('Reno Mo — THORN RECKONING');}};
  function drawEffects(){for(const a of game.volley){const q=1-a.left/.6,x=a.x+(a.target.x-a.x)*q,y=a.y+(a.target.y-25-a.y)*q-Math.sin(q*Math.PI)*90;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(a.target.y-25-a.y,a.target.x-a.x));ctx.strokeStyle='#b2ee68';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-26,0);ctx.lineTo(10,0);ctx.stroke();ctx.fillStyle='#d4ff82';ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(3,-6);ctx.lineTo(3,6);ctx.fill();ctx.restore();vfx.glow(x,y,20,'#8bec40',.5);}for(const b of game.hellfire)vfx.hellfireBomb(b,visualTime);for(const e of game.effects){if(e.kind==='queenPulse'){const q=e.age/e.life;ctx.save();ctx.globalAlpha=(1-q)*.65;ctx.strokeStyle=e.color;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(e.x,e.y,e.radius*q,e.radius*q*.42,0,0,Math.PI*2);ctx.stroke();ctx.restore();}else if(e.kind==='cleanse'){const q=e.age/e.life;ctx.save();ctx.globalAlpha=1-q;ctx.strokeStyle='#ffe9a1';ctx.shadowColor='#ffd24c';ctx.shadowBlur=16;ctx.lineWidth=3*(1-q)+1;ctx.beginPath();ctx.ellipse(e.x,e.y+35,18+q*65,8+q*26,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+q;const x=e.x+Math.cos(a)*(20+q*35),y=e.y+Math.sin(a)*24-q*65;ctx.fillStyle='#fff5d6';ctx.fillRect(x-2,y-5,4,10);ctx.fillRect(x-5,y-2,10,4);}ctx.restore();}else if(e.hellfire)vfx.hellfireImpact(e);else vfx.effect(e);}}
  function paint(){ctx.clearRect(0,0,1200,800);drawMap();drawPads();
    if(selectedTower){const t=selectedTower;ctx.save();ctx.strokeStyle=K.TYPES[t.type].color;ctx.fillStyle=K.TYPES[t.type].color+'12';ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(t.x,t.y,K.stats(t).range,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
    [...game.towers.map(t=>({y:t.y,draw:()=>drawTowers([t])})),...game.enemies.map(e=>({y:e.y,draw:()=>drawEnemies([e])}))].sort((a,b)=>a.y-b.y).forEach(s=>s.draw());
    for(const p of game.projectiles)vfx.projectile(p);drawEffects();window.drawKnollCampaign(ctx,game,actions,vfx,visualTime);
  }
  function updateUI(){
    updateQuick();
    cleanseBtn.hidden=false;cleanseBtn.textContent=game.stage!==3?'CLEANSE\nUnlocks at\nLevel 3':game.cleanseUsed?'CLEANSE\nUSED':'MAAHAA\nCLEANSE\n1 / 1';cleanseBtn.disabled=paused||game.stage!==3||game.status!=='wave'||game.cleanseUsed||!!game.ultimate||!game.towers.some(t=>t.type==='maahaa'&&t.hp>0)||!game.towers.some(t=>t.hp>0&&(t.hp<t.maxHp||t.poisonUntil>game.time||t.hexUntil>game.time||t.frozenUntil>game.time));

    const volleyLeft=Math.max(0,game.volleyUntil-game.time);volleyBtn.textContent=volleyLeft>0?'POISON VOLLEY\n'+volleyLeft.toFixed(1)+'s':game.volleyUsed?'POISON VOLLEY\nUSED':'FORDENAD\nPOISON VOLLEY\n1 / 1';volleyBtn.disabled=paused||game.status!=='wave'||game.volleyUsed||!!game.ultimate||!game.towers.some(t=>t.type==='fordenad')||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=K.WIDTH);
    const reverseLeft=Math.max(0,game.reverseUntil-game.time);reverseBtn.textContent=reverseLeft>0?'REVERSE\n'+reverseLeft.toFixed(1)+'s':game.reverseUsed?'REVERSE\nUSED':'HOST\nREVERSE\n1 / 1';reverseBtn.disabled=paused||game.status!=='wave'||game.reverseUsed||!!game.ultimate||!game.towers.some(t=>t.type==='host')||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=K.WIDTH);
    hellfireBtn.textContent=game.hellfireUsed?'HELLFIRE\nUSED':'OLD SAILOR\nHELLFIRE\n1 / 1';hellfireBtn.disabled=paused||game.status!=='wave'||game.hellfireUsed||!!game.ultimate||!game.towers.some(t=>t.type==='sailor')||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=1200);
    const freezeLeft=Math.max(0,game.freezeUntil-game.time);freezeBtn.textContent=freezeLeft>0?'TOTAL FREEZE\n'+freezeLeft.toFixed(1)+'s':game.freezeCharges<=0?'TOTAL FREEZE\nUSED':'KnowME\nTOTAL FREEZE\n'+game.freezeCharges+' / 2';freezeBtn.disabled=paused||game.status!=='wave'||game.freezeCharges<=0||freezeLeft>0||!!game.ultimate||!game.towers.some(t=>t.type==='knowme')||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=K.WIDTH);
    document.body.classList.toggle('ultimate-active',!!game.ultimate);$('#waveMax').textContent=K.stageWaves(game.stage);document.querySelectorAll('.tower-card').forEach(b=>{const locked=(K.TYPES[b.dataset.type].unlock||1)>game.stage;b.disabled=locked;b.title=locked?'Unlocks in Level '+K.TYPES[b.dataset.type].unlock:K.TYPES[b.dataset.type].power;});$('#renoBtn').disabled=paused||game.status!=='wave'||game.gold<1000||!!game.ultimate||game.ultimateCooldown>0||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=1200);$('#renoBtn').textContent=game.ultimate?'RENO MO\nUNLEASHED':game.ultimateCooldown>0?'RENO MO\n'+Math.ceil(game.ultimateCooldown)+'s':'RENO MO\nSUMMON\n✧ 1,000';const t=selectedTower,next=Math.min(K.stageWaves(game.stage),game.wave+1),plan=K.wavePlan(next,game.stage);
    $('#actionBtn').disabled=t?(t.level>=3||game.gold<K.upgradeCost(t)):game.gold<K.TYPES[selected].cost;if(t)$('#killStat').textContent=t.kills+' takedowns · HP '+Math.ceil(t.hp)+'/'+t.maxHp+((t.type==='lady'||t.type==='phil')?' · '+Math.ceil(Math.max(0,t.cooldown))+'s':'');
    $('#gold').textContent=Number(game.gold.toFixed(1));$('#lives').textContent=game.lives;$('#wave').textContent=game.wave;$('#waveCounter').textContent=String(next).padStart(2,'0')+' / '+K.stageWaves(game.stage);$('#bestRecord').textContent='LEVEL '+game.stage+' / 3';
    $('.map-number').textContent='0'+game.stage;$('.map-header h2').textContent=['','Forest Knoll','The Ashen Knoll','The Eclipse Citadel'][game.stage];document.body.classList.toggle('ashen',game.stage>=2);
    $('#phase').textContent=game.status==='wave'?'WAVE '+game.wave+' IN PROGRESS':game.status==='lost'?'SHRINE FALLEN':game.status==='won'?'CAMPAIGN COMPLETE':'PREPARE YOUR DEFENSE';
    $('#mapHint').textContent=placing?'Choose a clearing for '+K.TYPES[selected].name:game.stage>=2?(game.stage===3?'The citadel awakens. Defend the final shrine.':'The forest burns. The mutants march. Hold the pear.'):'Choose a guardian. Claim a clearing. Hold the line.';
    $('#enemyCount').textContent=game.status==='wave'?game.enemies.length+' on the trail':game.lastClear?'Wave '+game.lastClear.wave+' cleared · +'+game.lastClear.bonus+' gold':'Build before they arrive';
    $('#waveProgress').style.width=game.status==='wave'?Math.min(100,game.waveTime/(K.wavePlan(game.wave,game.stage).at(-1).at+8)*100)+'%':'0%';
    $('#waveName').textContent=next===K.stageWaves(game.stage)?'The final reckoning':plan.some(e=>e.kind==='boss')?'A crowned menace':'Flock '+next;
    $('#waveComposition').textContent=plan.length+(game.stage===3?' crystal enemies':game.stage===2?' mutated enemies':' enemies')+(plan.some(e=>e.kind==='boss')?' · BOSS':'')+(plan.some(e=>e.kind==='hexqueen')?' · HEX QUEEN':'');
    $('#waveDescription').textContent=game.stage>=2?'Mutant health ×'+(game.stage===3?'4.95':'1.904')+'. '+(game.stage===2?'Lady Never Scared unlocked.':'Phil Heal + Maahaa CLEANSE unlocked. Rare Hex Queens freeze and control nearby towers.')+' Gold carries over; rebuild your guardians.':'Enemy health reduced 10% (2.7× original). Poison arrives in wave 5 and slowly corrodes towers. Replace fallen guardians on their cleared pads.';
    $('#waveBtn').disabled=game.status!=='build';const label=game.status==='won'?'Campaign complete ✦':'Send wave '+next+' →';if($('#waveBtn').textContent!==label)$('#waveBtn').textContent=label;refreshPads();
  }
  function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  function handleEvents(){for(const e of game.events.splice(0)){if(['placed','upgraded','cleared','stage'].includes(e.type))saveCheckpoint();if(e.type==='towerDestroyed'){if(selectedTower===e.tower){selectedTower=null;placing=true;updateInspector();}toast(`${K.TYPES[e.tower.type].name} destroyed! Recruit a replacement.`);}if(e.type==='towerHit'&&selectedTower===e.tower)updateInspector();if(e.type==='queenSpell'&&e.count)toast(e.spell==='frost'?'HEX QUEEN · towers frozen for 5s':'HEX QUEEN · mind control for 10s — CLEANSE breaks it');if(e.type==='cast'){sfx.play(e.power)}if(e.type==='impact'){sfx.play(e.power,'impact')}if(e.type==='conversionStart'||e.type==='converted')sfx.play('lady');if(e.type==='ultimateStart')sfx.play('reno');if(e.type==='stage'){selectedTower=null;selectType('knowme');refreshPads();$('#stageDialog .eyebrow').textContent='LEVEL '+game.stage+' UNLOCKED';toast('LEVEL '+game.stage+' unlocked · +250 gold');$('#stageDialog h2').textContent=game.stage===2?'The Ashen Knoll':'The Eclipse Citadel';$('#stageDialog p:nth-of-type(2)').textContent=game.stage===2?'18 waves. Rebuild on a clean board; your gold carries over and Deep Freeze resets. Lady Never Scared joins.':'20 final waves. Rebuild on a clean board; your gold carries over and Deep Freeze resets. Phil Heal joins. Maahaa unlocks CLEANSE. Crystal enemies have 10% more health; rare Hex Queens freeze and control nearby towers.';$('#stageDialog').showModal();}if(e.type==='upgraded'){game.effects.push({kind:'cannon',x:e.tower.x,y:e.tower.y-75,radius:38,color:K.TYPES[e.tower.type].color,life:.7,age:0});toast(`${K.TYPES[e.tower.type].name} reached level ${e.tower.level}.`)}if(e.type==='cleared'){toast(`Wave cleared · +✧ ${e.bonus}${e.milestone?' · milestone +'+e.milestone+' included':''}${e.perfect?' · flawless':''}`)}if(e.type==='leak')toast(`A bird reached the pear · shrine −${e.amount}`);if(e.type==='won'||e.type==='lost')end(e.type)}}
  function end(kind){saveCheckpoint();window.dispatchEvent(new CustomEvent('knoll-run-ended',{detail:{kills:game.kills,stage:game.stage,wave:game.wave,won:kind==='won'}}));$('#endEyebrow').textContent=kind==='won'?'THE KNOLL HOLDS':'THE REALM FELL';$('#endTitle').textContent=kind==='won'?'A legendary little victory.':'The pear has fallen.';$('#endDescription').textContent=kind==='won'?'King Nibble has been sent home. All three stages are cleared. The pear endured 53 waves.':'The flock got through. Gather the guardians and try a new formation.';$('#endStats').innerHTML=`${game.kills} birds defeated <br>${Number(game.gold.toFixed(1))} gold banked <br>Level ${game.stage} · Wave ${game.wave} of ${K.stageWaves(game.stage)}`;$('#endDialog').showModal()}
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused&&!document.querySelector('dialog[open]')&&!document.hidden){visualTime+=dt*speed;const steps=Math.ceil(speed);for(let i=0;i<steps;i++)game.update(dt*speed/steps);}paint();updateUI();handleEvents();$('#playResources').textContent='✧ '+Math.floor(game.gold)+' · ♡ '+game.lives+' · Wave '+game.wave+'/'+K.stageWaves(game.stage);$('#playWaveBtn').disabled=$('#waveBtn').disabled;$('#playWaveBtn').textContent=$('#waveBtn').textContent;raf=requestAnimationFrame(loop)}
  $('#waveBtn').addEventListener('click',()=>{saveCheckpoint();if(game.startWave()){toast(`Wave ${game.wave} incoming.`);updateUI()}});$('#pauseBtn').addEventListener('click',()=>togglePause());$('#resumeBtn').addEventListener('click',()=>togglePause());$('#speedBtn').addEventListener('click',()=>{speed=speed===1?2:1;$('#speedBtn').textContent=speed+'×';toast(speed===2?'Double-time defense.':'Back to steady hands.')});$('#actionBtn').addEventListener('click',()=>{if(selectedTower){const d=K.TYPES[selectedTower.type];if(game.upgrade(selectedTower.id))toast(`${d.name} upgraded to ${roman[selectedTower.level]}.`);else toast('Not enough gold or already maxed.');updateInspector();updateUI();}else selectType(selected)});$('#sellBtn').addEventListener('click',()=>{if(selectedTower){game.sell(selectedTower.id);selectedTower=null;updateInspector();toast('Tower deleted · 50% refunded.');}});$('#targetBtn').addEventListener('click',()=>{if(selectedTower){selectedTower.targetMode=selectedTower.targetMode==='first'?'strongest':'first';updateInspector()}});
  function togglePause(){paused=!paused;$('#pauseOverlay').hidden=!paused;$('#pauseBtn').textContent=paused?'▶':'Ⅱ'}
  $('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#readyBtn').onclick=()=>$('#helpDialog').close();$('#restartBtn').onclick=()=>{$('#endDialog').close();game.reset();saveCheckpoint();paused=false;$('#pauseOverlay').hidden=true;$('#pauseBtn').textContent='Ⅱ';selectedTower=null;selectType('knowme');speed=1;$('#speedBtn').textContent='1×';toast('The knoll is yours to defend.')};$('#soundBtn').onclick=async()=>{sound=!sound;$('#soundBtn').setAttribute('aria-pressed',sound);$('#soundBtn').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('#soundBtn').textContent=sound?'FX ON':'FX OFF';if(sound){try{await sfx.enable();if(!sound)sfx.mute();else toast('FX on: ice, lightning and cannon only.');}catch{sound=false;sfx.mute();$('#soundBtn').setAttribute('aria-pressed','false');$('#soundBtn').textContent='FX OFF';$('#soundBtn').setAttribute('aria-label','Enable sound');toast('Audio could not load. Try again.');}}else sfx.mute();};$('#enterStageBtn').onclick=()=>$('#stageDialog').close();
  document.addEventListener('keydown',e=>{if(e.repeat||document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.key>='1'&&e.key<='7')selectType(cards[+e.key-1][0]);if(e.code==='Space'){e.preventDefault();if(game.status==='build')$('#waveBtn').click()}if(e.key.toLowerCase()==='p')togglePause();if(e.key==='Escape'){placing=false;selectedTower=null;updateInspector()}});
  loadAssets().then(()=>{let restored=false;try{restored=KnollCheckpoint.restore(game,localStorage.getItem(KnollCheckpoint.key),K);}catch{}ready=true;makeRoster();makePads();selectType('knowme');$('#loading').remove();if(restored)toast('Checkpoint restored — send the wave when ready.');paint();updateUI();raf=requestAnimationFrame(loop)}).catch(()=>{$('#loading').classList.add('failed');$('#loading p').textContent='The forest needs a refresh. Reload this page to try again.'});
})();
