(function(){
  'use strict';
  const K=window.KnollDefense, game=new K.Game(), canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
  const $=s=>document.querySelector(s), imgs={};
  const art={knowme:'assets/knowme.webp',host:'assets/host.webp',sailor:'assets/sailor.webp',maahaa:'assets/maahaa.webp',fordenad:'assets/fordenad.webp',lady:'assets/lady.webp',phil:'assets/phil.webp',reno:'assets/reno.webp',board:'assets/forest-expanded.webp',burnt:'assets/forest-burnt.webp',citadel:'assets/eclipse-citadel.webp'}; 
  const cards=[['knowme','1'],['host','2'],['sailor','3'],['maahaa','4'],['fordenad','5'],['lady','6'],['phil','7']]; let selected='knowme', selectedTower=null, placing=false, paused=false, speed=1, last=0, raf=0, toastTimer=0, sound=false;
  const sfx=new KnollAudio(),vfx=new KnollVFX(ctx),walks={},actions={};let visualTime=0;
  const roman=['','I','II','III'];
  function loadAssets(){return Promise.all([loadWalks(),...['lady','phil','reno','demon'].map(async k=>actions[k]=await loadActionSheet('assets/'+k+'-actions.webp')),...Object.entries(art).map(async([k,src])=>{if(['nibble','brute','boss','venom'].includes(k)){imgs[k]=await loadCharacter(src);return;}imgs[k]=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(src));im.src=src;});})]);}
  async function loadWalks(){await Promise.all(['base','hulk','venom','boss'].flatMap(kind=>['walk','mutant'].map(async prefix=>{walks[prefix+'-'+kind]=await loadWalkSheet('assets/'+prefix+'-'+kind+'.webp');})));}
  function makeRoster(){
    $('#roster').innerHTML=cards.map(([type,key])=>{const t=K.TYPES[type];return `<button class="tower-card" data-type="${type}"><div class="card-art"><img src="${art[type]}" alt="${t.name} gnome"><span class="card-key">${key}</span></div><div class="card-copy"><strong>${t.name}</strong><small>${t.power}</small><span class="card-cost">✧ ${t.cost}<em>+</em></span></div></button>`}).join('');
    document.querySelectorAll('.tower-card').forEach(b=>b.onclick=()=>selectType(b.dataset.type));
  }
  function selectType(type){if((K.TYPES[type].unlock||1)>game.stage){toast('Unlocks in Level '+K.TYPES[type].unlock);return;}selected=type;selectedTower=null;placing=true;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));updateInspector();paint();}
  function setTower(t){selectedTower=t;placing=false;selected=t.type;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===selected));updateInspector();paint();}
  function updateInspector(){const t=selectedTower, type=t?t.type:selected, d=K.TYPES[type], s=t?K.stats(t):{damage:d.damage,range:d.range,interval:d.interval};$('#inspectorEyebrow').textContent=t?'PLACED GUARDIAN':'MEET YOUR GUARDIAN';$('#levelLabel').textContent=t?roman[t.level]:'I';$('#towerName').textContent=d.name;$('#towerTitle').textContent=d.title.toUpperCase();$('#towerDescription').textContent=d.description;$('#powerBadge').textContent=d.power.toUpperCase();$('#portraitImage').src=art[type];$('#portraitImage').alt=d.name+' guardian';document.querySelector('.tower-stats span').textContent=type==='lady'?'HEAL / SEC':'DAMAGE';$('#damageStat').textContent=type==='lady'?4*(t?t.level:1):Math.round(s.damage);$('#targetBtn').hidden=type==='lady';$('#rangeStat').textContent=Math.round(s.range);$('#rateStat').textContent=(1/s.interval).toFixed(1)+'/s';$('#towerExtra').hidden=!t;$('#killStat').textContent=t?`${t.kills} takedowns · HP ${Math.ceil(t.hp)}/${t.maxHp}`:'';$('#targetBtn').textContent=t?`Target: ${t.targetMode} ↔`:'';$('#actionBtn').hidden=!!t;$('#sellBtn').hidden=!t;$('#sellBtn').textContent=t?`Dismiss guardian · recover ✧ ${Math.floor(t.spent*.7)}`:'';$('#placementNote').textContent=t?'Select a placed guardian to inspect or upgrade.':`Then choose an empty stone clearing · ✧ ${d.cost}`;if(t){const up=K.upgradeCost(t);$('#actionBtn').hidden=false;$('#actionBtn').innerHTML=t.level<3?`Upgrade to ${roman[t.level+1]} <span>✧ ${up}</span>`:'Fully upgraded';$('#actionBtn').disabled=t.level>=3||game.gold<up;$('#actionBtn').dataset.action='upgrade';}else{$('#actionBtn').hidden=false;$('#actionBtn').disabled=game.gold<d.cost;$('#actionBtn').innerHTML=`Recruit guardian <span>✧ ${d.cost}</span>`;$('#actionBtn').dataset.action='recruit';}}
  function makePads(){const wrap=$('#pads');wrap.innerHTML=K.PADS.map((p,i)=>`<button class="pad" data-pad="${i}" aria-label="Stone clearing ${i+1}"></button>`).join('');wrap.querySelectorAll('.pad').forEach((b,i)=>b.onclick=()=>{const t=game.towers.find(x=>x.pad===i);if(t){setTower(t);return}if(!placing){toast('Choose a guardian first.');return}const placed=game.place(selected,i);if(!placed)toast(game.gold<K.TYPES[selected].cost?'Not enough gold yet.':'That clearing is unavailable.');else{toast(`${K.TYPES[selected].name} took the clearing.`);selectedTower=placed;placing=false;updateInspector();}refreshPads();paint();});refreshPads();}
  function refreshPads(){document.querySelectorAll('.pad').forEach((b,i)=>{const t=game.towers.find(x=>x.pad===i),p=K.PADS[i];b.style.left=(p.x/12)+'%';b.style.top=(p.y/8)+'%';b.classList.toggle('occupied',!!t);b.title=t?`${K.TYPES[t.type].name} · level ${t.level}`:`Build on clearing ${i+1}`});}
  function drawMap(){const map=game.stage===3?imgs.citadel:game.stage===2?imgs.burnt:imgs.board;ctx.drawImage(map,0,0,map.width,map.height*.2,0,0,1200,224);ctx.drawImage(map,0,map.height*.2,map.width,map.height*.8,0,224,1200,640);if(game.stage===2)drawFlames();}
  function drawFlames(){ctx.save();ctx.globalCompositeOperation='screen';for(let i=1;i<K.PATH.length-1;i+=2){const p=K.PATH[i],n=K.PATH[i+1],len=Math.hypot(n[0]-p[0],n[1]-p[1]);for(const side of [-1,1]){const x=p[0]-(n[1]-p[1])/len*48*side,y=p[1]+(n[0]-p[0])/len*48*side;for(let j=0;j<3;j++){const phase=visualTime*5+i+j*2,height=20+12*Math.sin(phase);ctx.fillStyle=j===2?'#ffe9a9bb':j===1?'#ffad3199':'#fa431766';ctx.beginPath();ctx.moveTo(x-9+j*2,y);ctx.quadraticCurveTo(x-16+Math.sin(phase)*7,y-height*.6,x+Math.sin(phase)*9,y-height-12);ctx.quadraticCurveTo(x+16,y-height*.4,x+9-j*2,y);ctx.fill();}}}ctx.restore();}
  function pathStroke(){ctx.beginPath();ctx.moveTo(...K.PATH[0]);for(const p of K.PATH.slice(1))ctx.lineTo(...p);}
  function drawPads(){for(let i=0;i<K.PADS.length;i++){const p=K.PADS[i],t=game.towers.find(x=>x.pad===i);if(t)continue;ctx.fillStyle='rgba(210,225,168,.35)';ctx.beginPath();ctx.ellipse(p.x,p.y,31,19,0,0,7);ctx.fill();ctx.strokeStyle='rgba(56,82,50,.65)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#d8ddbd';ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.fillText(String(i+1),p.x,p.y+4);ctx.textAlign='left';}}
  function sprite(im,x,y,w,h,alpha=1){if(!im)return;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x-w/2,y-h,w,h);ctx.restore()}
  function drawTowers(towers=game.towers){for(const t of towers){
    ctx.fillStyle='#182820';ctx.fillRect(t.x-25,t.y+23,50,5);ctx.fillStyle=t.hp<t.maxHp*.4?'#ff795e':'#91d99d';ctx.fillRect(t.x-25,t.y+23,50*t.hp/t.maxHp,5);
    const d=K.TYPES[t.type],scale=1+(t.level-1)*.06,clock=game.time+t.id,bob=t.type==='host'?Math.sin(clock*3)*4:Math.sin(clock*2)*1.5;
    ctx.fillStyle='#162f1e55';ctx.beginPath();ctx.ellipse(t.x,t.y+2,33,11,0,0,7);ctx.fill();
    sprite(actions[t.type]?actions[t.type][t.castUntil>game.time?Math.min(3,1+Math.floor((game.time-t.castStart)/.65)):0]:imgs[t.type],t.x-(t.type==='sailor'?t.recoil*7:0),t.y-bob,(actions[t.type]?150:105)*scale,145*scale);
    ctx.save();ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.shadowColor=d.color;ctx.shadowBlur=12;ctx.globalAlpha=.55;
    if(t.type==='knowme'){for(let i=0;i<6;i++){const a=clock+i*1.05;ctx.beginPath();ctx.arc(t.x+Math.cos(a)*32,t.y-55+Math.sin(a)*18,2+i%2,0,7);ctx.fill();}}
    if(t.type==='host'){ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t.x,t.y-65,42,13,Math.sin(clock)*.4,0,Math.PI*2);ctx.stroke();}
    if(t.type==='maahaa'){ctx.translate(t.x+17,t.y-120*scale);ctx.rotate(clock*.5);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(18+t.recoil*12,0);ctx.stroke();}}
    if(t.type==='fordenad'){for(let i=0;i<4;i++){const a=clock*.7+i*Math.PI/2;ctx.save();ctx.translate(t.x+Math.cos(a)*27,t.y-20+Math.sin(a)*9);ctx.rotate(a);ctx.beginPath();ctx.ellipse(0,0,6,2,0,0,7);ctx.fill();ctx.restore();}}
    if(t.type==='sailor'&&t.recoil>0){ctx.globalAlpha=t.recoil*.5;ctx.fillStyle='#e5dab8';ctx.beginPath();ctx.arc(t.x+32,t.y-73-(1-t.recoil)*20,4+(1-t.recoil)*12,0,7);ctx.fill();}
    ctx.restore();ctx.fillStyle=d.color;ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(roman[t.level],t.x,t.y+18);ctx.textAlign='left';
  }}

  function drawEnemies(enemies=game.enemies){for(const e of enemies){if(e.hp<=0)continue;const kind=e.kind==='brute'?'hulk':['boss','venom'].includes(e.kind)?e.kind:'base',frames=walks[(e.mutated?'mutant':'walk')+'-'+kind],im=frames[Math.floor(e.progress/10+e.id)%4],h=105*e.size,w=h*im.width/im.height,bob=0;ctx.fillStyle='#10221966';ctx.beginPath();ctx.ellipse(e.x,e.y+2,w*.35,8,0,0,7);ctx.fill();ctx.save();ctx.translate(e.x,e.y);if(e.direction<0)ctx.scale(-1,1);sprite(im,0,bob,w,h);ctx.restore();vfx.frozen(e,game.time,h,w);ctx.fillStyle='#182820';ctx.fillRect(e.x-22,e.y-h-5,44,4);ctx.fillStyle=e.enraged?'#ff834d':e.kind==='venom'?'#8dff91':e.kind==='boss'?'#ffd569':'#c5e98f';ctx.fillRect(e.x-22,e.y-h-5,44*Math.max(0,e.hp/e.maxHp),4);if(e.slowUntil>game.time||e.poisonUntil>game.time){ctx.strokeStyle=e.poisonUntil>game.time?'#9ff46c':'#8ffff2';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y,24,8,0,0,7);ctx.stroke();}}}
  $('#renoBtn').onclick=()=>{if(!paused&&game.summonReno()){$('#arena').scrollIntoView({behavior:'instant',block:'center'});toast('Reno Mo — THORN RECKONING');}};
  function drawEffects(){for(const e of game.effects)vfx.effect(e);}
  function paint(){ctx.clearRect(0,0,1200,800);drawMap();drawPads();
    if(selectedTower){const t=selectedTower;ctx.save();ctx.strokeStyle=K.TYPES[t.type].color;ctx.fillStyle=K.TYPES[t.type].color+'12';ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(t.x,t.y,K.stats(t).range,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
    [...game.towers.map(t=>({y:t.y,draw:()=>drawTowers([t])})),...game.enemies.map(e=>({y:e.y,draw:()=>drawEnemies([e])}))].sort((a,b)=>a.y-b.y).forEach(s=>s.draw());
    for(const p of game.projectiles)vfx.projectile(p);drawEffects();window.drawKnollCampaign(ctx,game,actions,vfx,visualTime);
  }
  function updateUI(){
    document.body.classList.toggle('ultimate-active',!!game.ultimate);$('#waveMax').textContent=K.stageWaves(game.stage);document.querySelectorAll('.tower-card').forEach(b=>{const locked=(K.TYPES[b.dataset.type].unlock||1)>game.stage;b.disabled=locked;b.title=locked?'Unlocks in Level '+K.TYPES[b.dataset.type].unlock:K.TYPES[b.dataset.type].power;});$('#renoBtn').disabled=paused||game.status!=='wave'||game.gold<2500||!!game.ultimate||game.ultimateCooldown>0||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=1200);$('#renoBtn').textContent=game.ultimate?'Reno Mo · UNLEASHED':game.ultimateCooldown>0?'Reno Mo · '+Math.ceil(game.ultimateCooldown)+'s':'Summon Reno Mo · ✧ 2500';const t=selectedTower,next=Math.min(K.stageWaves(game.stage),game.wave+1),plan=K.wavePlan(next,game.stage);
    $('#actionBtn').disabled=t?(t.level>=3||game.gold<K.upgradeCost(t)):game.gold<K.TYPES[selected].cost;if(t)$('#killStat').textContent=t.kills+' takedowns · HP '+Math.ceil(t.hp)+'/'+t.maxHp+((t.type==='lady'||t.type==='phil')?' · '+Math.ceil(Math.max(0,t.cooldown))+'s':'');
    $('#gold').textContent=game.gold;$('#lives').textContent=game.lives;$('#wave').textContent=game.wave;$('#waveCounter').textContent=String(next).padStart(2,'0')+' / '+K.stageWaves(game.stage);$('#bestRecord').textContent='LEVEL '+game.stage+' / 3';
    $('.map-number').textContent='0'+game.stage;$('.map-header h2').textContent=['','Forest Knoll','The Ashen Knoll','The Eclipse Citadel'][game.stage];document.body.classList.toggle('ashen',game.stage>=2);
    $('#phase').textContent=game.status==='wave'?'WAVE '+game.wave+' IN PROGRESS':game.status==='lost'?'SHRINE FALLEN':game.status==='won'?'CAMPAIGN COMPLETE':'PREPARE YOUR DEFENSE';
    $('#mapHint').textContent=placing?'Choose a clearing for '+K.TYPES[selected].name:game.stage>=2?(game.stage===3?'The citadel awakens. Defend the final shrine.':'The forest burns. The mutants march. Hold the pear.'):'Choose a guardian. Claim a clearing. Hold the line.';
    $('#enemyCount').textContent=game.status==='wave'?game.enemies.length+' on the trail':'Build before they arrive';
    $('#waveProgress').style.width=game.status==='wave'?Math.min(100,game.waveTime/(K.wavePlan(game.wave,game.stage).at(-1).at+8)*100)+'%':'0%';
    $('#waveName').textContent=next===K.stageWaves(game.stage)?'The final reckoning':plan.some(e=>e.kind==='boss')?'A crowned menace':'Flock '+next;
    $('#waveComposition').textContent=plan.length+(game.stage>=2?' mutated enemies':' enemies')+(plan.some(e=>e.kind==='boss')?' · BOSS':'');
    $('#waveDescription').textContent=game.stage>=2?'Mutant health ×'+(game.stage===3?'4.5':'3.4')+'. '+(game.stage===2?'Lady Never Scared unlocked.':'Phil Heal unlocked.')+' Guardians carry over.':'Enemies now have 3× health. Poison arrives in wave 5 and slowly corrodes towers. Replace fallen guardians on their cleared pads.';
    $('#waveBtn').disabled=game.status!=='build';const label=game.status==='won'?'Campaign complete ✦':'Send wave '+next+' →';if($('#waveBtn').textContent!==label)$('#waveBtn').textContent=label;refreshPads();
  }
  function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  function handleEvents(){for(const e of game.events.splice(0)){if(e.type==='towerDestroyed'){if(selectedTower===e.tower){selectedTower=null;placing=true;updateInspector();}toast(`${K.TYPES[e.tower.type].name} destroyed! Recruit a replacement.`);}if(e.type==='towerHit'&&selectedTower===e.tower)updateInspector();if(e.type==='cast'){sfx.play(e.power)}if(e.type==='impact'){sfx.play(e.power,'impact')}if(e.type==='conversionStart'||e.type==='converted')sfx.play('lady');if(e.type==='ultimateStart')sfx.play('reno');if(e.type==='stage'){toast('LEVEL '+game.stage+' unlocked · +250 gold');$('#stageDialog h2').textContent=game.stage===2?'The Ashen Knoll':'The Eclipse Citadel';$('#stageDialog p:nth-of-type(2)').textContent=game.stage===2?'18 waves. Lady Never Scared joins: heal neighbors and convert mutants.':'20 final waves. Phil Heal joins with neon shadow uppercuts.';$('#stageDialog').showModal();}if(e.type==='upgraded'){game.effects.push({kind:'cannon',x:e.tower.x,y:e.tower.y-75,radius:38,color:K.TYPES[e.tower.type].color,life:.7,age:0});toast(`${K.TYPES[e.tower.type].name} reached level ${e.tower.level}.`)}if(e.type==='cleared'){toast(`Wave cleared · +✧ ${e.bonus}${e.perfect?' · flawless':''}`)}if(e.type==='leak')toast(`A bird reached the pear · shrine −${e.amount}`);if(e.type==='won'||e.type==='lost')end(e.type)}}
  function end(kind){$('#endEyebrow').textContent=kind==='won'?'THE KNOLL HOLDS':'THE REALM FELL';$('#endTitle').textContent=kind==='won'?'A legendary little victory.':'The pear has fallen.';$('#endDescription').textContent=kind==='won'?'King Nibble has been sent home. All three stages are cleared. The pear endured 53 waves.':'The flock got through. Gather the guardians and try a new formation.';$('#endStats').innerHTML=`${game.kills} birds defeated <br>${game.gold} gold banked <br>Level ${game.stage} · Wave ${game.wave} of ${K.stageWaves(game.stage)}`;$('#endDialog').showModal()}
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused&&!document.querySelector('dialog[open]')&&!document.hidden){visualTime+=dt;for(let i=0,n=game.ultimate?1:speed;i<n;i++)game.update(dt);}paint();updateUI();handleEvents();raf=requestAnimationFrame(loop)}
  $('#waveBtn').addEventListener('click',()=>{if(game.startWave()){toast(`Wave ${game.wave} incoming.`);updateUI()}});$('#pauseBtn').addEventListener('click',()=>togglePause());$('#resumeBtn').addEventListener('click',()=>togglePause());$('#speedBtn').addEventListener('click',()=>{speed=speed===1?2:1;$('#speedBtn').textContent=speed+'×';toast(speed===2?'Double-time defense.':'Back to steady hands.')});$('#actionBtn').addEventListener('click',()=>{if(selectedTower){const d=K.TYPES[selectedTower.type];if(game.upgrade(selectedTower.id))toast(`${d.name} upgraded to ${roman[selectedTower.level]}.`);else toast('Not enough gold or already maxed.');updateInspector();updateUI();}else selectType(selected)});$('#sellBtn').addEventListener('click',()=>{if(selectedTower){game.sell(selectedTower.id);selectedTower=null;updateInspector();toast('Guardian dismissed.');}});$('#targetBtn').addEventListener('click',()=>{if(selectedTower){selectedTower.targetMode=selectedTower.targetMode==='first'?'strongest':'first';updateInspector()}});
  function togglePause(){paused=!paused;$('#pauseOverlay').hidden=!paused;$('#pauseBtn').textContent=paused?'▶':'Ⅱ'}
  $('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#readyBtn').onclick=()=>$('#helpDialog').close();$('#restartBtn').onclick=()=>{$('#endDialog').close();game.reset();paused=false;$('#pauseOverlay').hidden=true;$('#pauseBtn').textContent='Ⅱ';selectedTower=null;selectType('knowme');speed=1;$('#speedBtn').textContent='1×';toast('The knoll is yours to defend.')};$('#soundBtn').onclick=async()=>{sound=!sound;$('#soundBtn').setAttribute('aria-pressed',sound);$('#soundBtn').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('#soundBtn').textContent=sound?'🔊':'♫';if(sound){try{await sfx.enable();if(!sound)sfx.mute();else toast('Magic sound effects enabled.');}catch{sound=false;sfx.mute();$('#soundBtn').setAttribute('aria-pressed','false');$('#soundBtn').textContent='♫';toast('Audio could not load. Try again.');}}else sfx.mute();};$('#enterStageBtn').onclick=()=>$('#stageDialog').close();
  document.addEventListener('keydown',e=>{if(e.repeat||document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.key>='1'&&e.key<='7')selectType(cards[+e.key-1][0]);if(e.code==='Space'){e.preventDefault();if(game.status==='build')$('#waveBtn').click()}if(e.key.toLowerCase()==='p')togglePause();if(e.key==='Escape'){placing=false;selectedTower=null;updateInspector()}});
  loadAssets().then(()=>{makeRoster();makePads();selectType('knowme');$('#loading').remove();paint();updateUI();raf=requestAnimationFrame(loop)}).catch(()=>{$('#loading').classList.add('failed');$('#loading p').textContent='The forest needs a refresh. Reload this page to try again.'});
})();
